(**************************************************************************)
(*                                                                        *)
(*                        SuperBOL OSS Studio                             *)
(*                                                                        *)
(*  Copyright (c) 2022-2026 OCamlPro SAS                                  *)
(*                                                                        *)
(* All rights reserved.                                                   *)
(* This source code is licensed under the GNU Affero General Public       *)
(* License version 3 found in the LICENSE.md file in the root directory   *)
(* of this source tree.                                                   *)
(*                                                                        *)
(**************************************************************************)

open Ctypes

(* This Types_generated module is an instantiation of the Types functor defined
   in the libcob_types.ml file.  It's generated by a C program that Dune creates
   and runs behind the scenes. *)
module Types = Libcob_types_generated

module Functions (Foreign: Ctypes.FOREIGN) = struct
  open Foreign

  let move =
    foreign "cob_move" @@
      ptr Types.cob_field @-> ptr Types.cob_field @-> returning void

end
