(**************************************************************************)
(*                                                                        *)
(*                        SuperBOL OSS Studio                             *)
(*                                                                        *)
(*  Copyright (c) 2022-2023 OCamlPro SAS                                  *)
(*                                                                        *)
(* All rights reserved.                                                   *)
(* This source code is licensed under the GNU Affero General Public       *)
(* License version 3 found in the LICENSE.md file in the root directory   *)
(* of this source tree.                                                   *)
(*                                                                        *)
(**************************************************************************)

open EzCompat                                                    (* StringMap *)
open Lsp.Types
open Lsp_testing

let complete_positions (doc, positions) : string -> unit =
  let { end_with_postproc; projdir }, server = make_lsp_project () in
  let server, prog = add_cobol_doc server ~projdir "prog.cob" doc in
  (* let doc = LSP.Server.find_document prog server in *)
  let location_as_srcloc = new srcloc_resuscitator_cache in
  let completions_at_position ?key (position: Position.t) =
    let location =
      let range = Range.create ~start:position ~end_:position in
      Location.create ~range ~uri:prog.uri
    in
    let params = CompletionParams.create ~position ~textDocument:prog () in
    Pretty.out "%a%a(line %d, character %d):\n"
      location_as_srcloc#pp location
      Fmt.(option ~none:nop (string ++ sp)) key
      position.line position.character;
    match LSP.Request.complete server params with
    | None ->
        Pretty.out "Failed completion@."
    | Some `CompletionList { items; _ } when items == [] ->
        Pretty.out "Empty completion list@."
    | Some `CompletionList { items; _ } ->
        let pp_comp_item ppf (item: CompletionItem.t) =
          Fmt.string ppf item.label in
        Pretty.out "List of completions: [%a]\n" (Fmt.list ~sep:(Fmt.any ";") pp_comp_item) items;

  in
  StringMap.iter (fun n p -> completions_at_position ~key:n p) positions.pos_map;
  List.iter (fun p -> completions_at_position p) positions.pos_anonymous;
  end_with_postproc
;;

let%expect_test "empty-file-completion" =
  let end_with_postproc = complete_positions @@ extract_position_markers {cobol|
_|_
    |cobol} in
  end_with_postproc [%expect.output];
  [%expect {|
    {"params":{"diagnostics":[],"uri":"file://__rootdir__/prog.cob"},"method":"textDocument/publishDiagnostics","jsonrpc":"2.0"}
    __rootdir__/prog.cob:2.0:
       1
       2 >
    ----   ^
       3
    (line 1, character 0):
    List of completions: [PROGRAM-ID;INTERFACE-ID;IDENTIFICATION;ID;FUNCTION-ID;CONTROL;CLASS-ID] |}]

let%expect_test "basic-completion" =
  let end_with_postproc = complete_positions @@ extract_position_markers {cobol|
        _|_IDENTIFICATION D_|_IVISION_|_._|_
        PROGRAM_|_-ID. prog.
        DATA DIV_|_ISION.
        WORKING-STORAGE _|_SECTION.
        01 _|_DATA-NAME _|_PIC X.
        _|_PROCEDU_|_RE _|_DIVISION.
          _|_DISPLAY _|_DATA-NAME
          _|_STOP _|_RUN._|_
  |cobol} in
  end_with_postproc [%expect.output];
  [%expect {|
    {"params":{"diagnostics":[],"uri":"file://__rootdir__/prog.cob"},"method":"textDocument/publishDiagnostics","jsonrpc":"2.0"}
    __rootdir__/prog.cob:2.8:
       1
       2 >         IDENTIFICATION DIVISION.
    ----           ^
       3           PROGRAM-ID. prog.
       4           DATA DIVISION.
    (line 1, character 8):
    List of completions: [PROGRAM-ID;INTERFACE-ID;IDENTIFICATION;ID;FUNCTION-ID;CONTROL;CLASS-ID]
    __rootdir__/prog.cob:2.24:
       1
       2 >         IDENTIFICATION DIVISION.
    ----                           ^
       3           PROGRAM-ID. prog.
       4           DATA DIVISION.
    (line 1, character 24):
    List of completions: [DIVISION]
    __rootdir__/prog.cob:2.31:
       1
       2 >         IDENTIFICATION DIVISION.
    ----                                  ^
       3           PROGRAM-ID. prog.
       4           DATA DIVISION.
    (line 1, character 31):
    List of completions: [DIVISION]
    __rootdir__/prog.cob:2.32:
       1
       2 >         IDENTIFICATION DIVISION.
    ----                                   ^
       3           PROGRAM-ID. prog.
       4           DATA DIVISION.
    (line 1, character 32):
    List of completions: [DIVISION]
    __rootdir__/prog.cob:3.15:
       1
       2           IDENTIFICATION DIVISION.
       3 >         PROGRAM-ID. prog.
    ----                  ^
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
    (line 2, character 15):
    List of completions: [SECURITY;REMARKS;PROGRAM-ID;INTERFACE-ID;INSTALLATION;FUNCTION-ID;DATE-WRITTEN;DATE-MODIFIED;DATE-COMPILED;CLASS-ID;AUTHOR]
    __rootdir__/prog.cob:4.16:
       1
       2           IDENTIFICATION DIVISION.
       3           PROGRAM-ID. prog.
       4 >         DATA DIVISION.
    ----                   ^
       5           WORKING-STORAGE SECTION.
       6           01 DATA-NAME PIC X.
    (line 3, character 16):
    List of completions: [DIVISION]
    __rootdir__/prog.cob:5.24:
       2           IDENTIFICATION DIVISION.
       3           PROGRAM-ID. prog.
       4           DATA DIVISION.
       5 >         WORKING-STORAGE SECTION.
    ----                           ^
       6           01 DATA-NAME PIC X.
       7           PROCEDURE DIVISION.
    (line 4, character 24):
    List of completions: [SECTION]
    __rootdir__/prog.cob:6.11:
       3           PROGRAM-ID. prog.
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
       6 >         01 DATA-NAME PIC X.
    ----              ^
       7           PROCEDURE DIVISION.
       8             DISPLAY DATA-NAME
    (line 5, character 11):
    List of completions: [VARYING;VALUES;VALUE;VAL-STATUS;USAGE;TYPEDEF;TYPE;TRAILING;SYNCHRONIZED;SIGN;SELECT;SAME;REDEFINES;PROPERTY;PROGRAM-POINTER;PROCEDURE-POINTER;PRESENT;POINTER;PICTURE;PACKED-DECIMAL;OCCURS;OBJECT;NATIONAL;LEADING;JUSTIFIED;IS TYPEDEF;IS GLOBAL;IS EXTERNAL;INVALID;INDEX;GROUP-USAGE;GLOBAL;FUNCTION-POINTER;FLOAT-SHORT;FLOAT-LONG;FLOAT-EXTENDED;FLOAT-DECIMAL-34;FLOAT-DECIMAL-16;FLOAT-BINARY-64;FLOAT-BINARY-32;FLOAT-BINARY-128;FILLER;EXTERNAL;DYNAMIC;DISPLAY;DESTINATION;DEFAULT;COMP-X;COMP-N;COMP-9;COMP-6;COMP-5;COMP-4;COMP-3;COMP-2;COMP-15;COMP-10;COMP-1;COMP-0;COMP;CLASS;BLANK;BIT;BINARY-SHORT;BINARY-LONG;BINARY-DOUBLE;BINARY-C-LONG;BINARY-CHAR;BINARY;BASED;ANY;ALIGNED]
    __rootdir__/prog.cob:6.21:
       3           PROGRAM-ID. prog.
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
       6 >         01 DATA-NAME PIC X.
    ----                        ^
       7           PROCEDURE DIVISION.
       8             DISPLAY DATA-NAME
    (line 5, character 21):
    List of completions: [ZERO-FILL;ZEROS;WRITE;WORKING-STORAGE;WITH NO ADVANCING;WITH DATA;WITH;WHEN;VARYING;VALUES;VALUE;VAL-STATUS;VALIDATE;USING;USER-DEFAULT;USAGE;UPPER;UPON;UPDATE;UP;UNTIL;UNSTRING;UNLOCK;UNIT;UNDERLINE;TYPEDEF;TYPE;TRANSFORM;TRAILING-SIGN;TRAILING;TOP;TO;TIME-OUT;TIMES;THRU;THEN;TEXT;TEST;TERMINATE;TERMINAL;TALLYING;SYSTEM-OFFSET;SYSTEM-DEFAULT;SYNCHRONIZED;SYMBOLIC;SUPPRESS;SUPER;SUM;SUB-QUEUE-3;SUB-QUEUE-2;SUB-QUEUE-1;SUBTRACT;STRING;STOP;STEP;STATUS;START;SPACE-FILL;SPACES;SOURCES;SOURCE;SORT;SIZE;SIGNED;SIGN;SHORT;SHARING;SET;SEQUENTIAL;SEQUENCE;SEND;SELF;SELECT;SEGMENT-LIMIT;SEGMENT;SECURE;SECTION;SECONDS;SEARCH;SD;SCREEN;SAME;ROUNDED;RIGHT-JUSTIFY;REWRITE;REVERSE-VIDEO;REVERSED;RETURNING;RETURN;RETRY;RESUME;RESET;RESERVE;RERUN;REQUIRED;REPORTS;REPORT;REPLACING;RENAMES;REMAINDER;RELEASE;RELATIVE;REFERENCE;REEL;REDEFINES;RECORDS;RECORDING;RECORD;RECEIVE;READ;RAISING;RAISE;QUOTES;QUEUE;PURGE;PROPERTY;PROMPT;PROGRAM-POINTER;PROGRAM;PROCEDURE-POINTER;PROCEDURE;PREVIOUS;PRESENT;PREFIXED;POSITIVE;POSITION;POINTER;PICTURE;PHYSICAL;PERFORM;PAGE-COUNTER;PAGE;PADDING;PACKED-DECIMAL;OVERRIDE;OVERLINE;OVERFLOW;OUTPUT;ORGANIZATION;ORDER;OR;OPTIONS;OPTIONAL;OPEN;ON SIZE ERROR;ON OVERFLOW;ON EXCEPTION;ONLY;ON;OMITTED;OFF;OF;OCCURS;OBJECT-REFERENCE;OBJECT;NUMERIC-EDITED;NUMERIC;NULL;NO-ECHO;NO DATA;NOT ON SIZE ERROR;NOT ON OVERFLOW;NOT ON EXCEPTION;NOT INVALID KEY;NOT AT EOP;NOT AT END;NOT;NO;NEXT SENTENCE;NEXT;NEGATIVE;NEAREST-TO-ZERO;NATIONAL-EDITED;NATIONAL;MULTIPLY;MULTIPLE;MOVE;MODE;MESSAGE;MERGE;MEMORY;LOW-VALUES;LOWLIGHT;LOWER;LOCK;LOCAL-STORAGE;LOCALE;LINKAGE;LINE-COUNTER;LINES;LINE;LINAGE-COUNTER;LINAGE;LIMIT;LESS;LENGTH;LEFT-JUSTIFY;LEFTLINE;LEADING;LAST;LABEL;KEY;JUSTIFIED;I-O-CONTROL;I-O;IS TYPEDEF;IS GLOBAL;IS EXTERNAL;IS;IN-ARITHMETIC-RANGE;INVOKE;INVALID KEY;INVALID;INTRINSIC;INTO;INTERFACE;INSPECT;INPUT-OUTPUT;INPUT;INITIATE;INITIALIZED;INITIALIZE;INITIAL;INDEXED;INDEX;IN;IGNORING;IF;HIGH-VALUES;HIGHLIGHT;GROUP-USAGE;GROUP;GRID;GREATER;GOBACK;GO;GLOBAL;GIVING;GENERATE;FUNCTION-POINTER;FUNCTION;FULL;FROM;FREE;FORMAT;FOREVER;FOREGROUND-COLOR;FOR;FOOTING;FLOAT-SHORT;FLOAT-NOT-A-NUMBER-SIGNALING;FLOAT-NOT-A-NUMBER-QUIET;FLOAT-NOT-A-NUMBER;FLOAT-LONG;FLOAT-INFINITY;FLOAT-EXTENDED;FLOAT-DECIMAL-34;FLOAT-DECIMAL-16;FLOAT-BINARY-64;FLOAT-BINARY-32;FLOAT-BINARY-128;FIRST;FINAL;FILLER;FILE-CONTROL;FILE;FD;FARTHEST-FROM-ZERO;FALSE;FACTORY;EXTERNAL;EXTEND;EXPANDS;EXIT;EXCEPTION-OBJECT;EXCEPTION;EVERY;EVALUATE;ESI;ERROR;ERASE;EQUAL;EOP;ENVIRONMENT;ENTRY;ENTER;END-WRITE;END-UNSTRING;END-SUBTRACT;END-STRING;END-START;END-SEARCH;END-REWRITE;END-RETURN;END-RECEIVE;END-READ;END-PERFORM;END-OF-PAGE;END-MULTIPLY;END-IF;END-EVALUATE;END-DIVIDE;END-DISPLAY;END-DELETE;END-COMPUTE;END-CALL;END-ADD;END-ACCEPT;END;ENABLE;EMI;ELSE;EGI;DYNAMIC;DUPLICATES;DOWN;DIVIDE;DISPLAY;DISABLE;DESTINATION;DESCENDING;DEPENDING;DELIMITER;DELIMITED;DELETE;DEFAULT;DECIMAL-POINT;DEBUGGING;DATA RECORDS;DATA RECORD;DATA-POINTER;DATA;CURSOR;CURRENCY;CRT;COUNT;CONVERTING;CONTROLS;CONTROL;CONTINUE;CONTENT;CONSTANT;CONFIGURATION;COMP-X;COMP-N;COMP-9;COMP-6;COMP-5;COMP-4;COMP-3;COMP-2;COMP-15;COMP-10;COMP-1;COMP-0;COMPUTE;COMP;COMMUNICATION;COLS;COLUMN;COLLATING;COL;CODE-SET;CODE;CLOSE;CLASSIFICATION;CLASS;CHARACTERS;CHARACTER;CANCEL;CALL;B-XOR;B-OR;B-NOT;B-AND;BY;BOTTOM;BOOLEAN;BLOCK;BLINK;BLANK;BIT;BINARY-SHORT;BINARY-LONG;BINARY-DOUBLE;BINARY-C-LONG;BINARY-CHAR;BINARY;BELL;BEFORE;BASED;BACKGROUND-COLOR;AUTO;AT EOP;AT END;ATTRIBUTE;AT;ASSIGN;ASCENDING;AS;ARE;ANY;AND;ALTERNATE;ALTER;ALSO;ALPHANUMERIC-EDITED;ALPHANUMERIC;ALPHABETIC-UPPER;ALPHABETIC-LOWER;ALPHABETIC;ALPHABET;ALLOCATE;ALL;ALIGNED;AFTER;ADVANCING;ADDRESS;ADD;ACCESS;ACCEPT]
    __rootdir__/prog.cob:7.8:
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
       6           01 DATA-NAME PIC X.
       7 >         PROCEDURE DIVISION.
    ----           ^
       8             DISPLAY DATA-NAME
       9             STOP RUN.
    (line 6, character 8):
    List of completions: [WORKING-STORAGE;SD;SCREEN;REPORT;PROGRAM-ID;PROCEDURE;LOCAL-STORAGE;LINKAGE;IDENTIFICATION;ID;FILE;FD;END;DATA;COMMUNICATION;CD]
    __rootdir__/prog.cob:7.15:
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
       6           01 DATA-NAME PIC X.
       7 >         PROCEDURE DIVISION.
    ----                  ^
       8             DISPLAY DATA-NAME
       9             STOP RUN.
    (line 6, character 15):
    List of completions: [WORKING-STORAGE;SD;SCREEN;REPORT;PROGRAM-ID;PROCEDURE;LOCAL-STORAGE;LINKAGE;IDENTIFICATION;ID;FILE;FD;END;DATA;COMMUNICATION;CD]
    __rootdir__/prog.cob:7.18:
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
       6           01 DATA-NAME PIC X.
       7 >         PROCEDURE DIVISION.
    ----                     ^
       8             DISPLAY DATA-NAME
       9             STOP RUN.
    (line 6, character 18):
    List of completions: [DIVISION]
    __rootdir__/prog.cob:8.10:
       5           WORKING-STORAGE SECTION.
       6           01 DATA-NAME PIC X.
       7           PROCEDURE DIVISION.
       8 >           DISPLAY DATA-NAME
    ----             ^
       9             STOP RUN.
      10
    (line 7, character 10):
    List of completions: [WRITE;VALIDATE;UNSTRING;UNLOCK;TRANSFORM;TERMINATE;SUPPRESS;SUBTRACT;STRING;STOP;START;SORT;SET;SEND;SEARCH;REWRITE;RETURN;RESUME;RELEASE;RECEIVE;READ;RAISE;PURGE;PROGRAM-ID;PERFORM;OPEN;NEXT SENTENCE;MULTIPLY;MOVE;MERGE;INVOKE;INSPECT;INITIATE;INITIALIZE;IF;IDENTIFICATION;ID;GOBACK;GO;GENERATE;FREE;EXIT;EVALUATE;ENTRY;ENTER;END;ENABLE;DIVIDE;DISPLAY;DISABLE;DELETE;DECLARATIVES;CONTINUE;COMPUTE;CLOSE;CANCEL;CALL;ALTER;ALLOCATE;ADD;ACCEPT]
    __rootdir__/prog.cob:8.18:
       5           WORKING-STORAGE SECTION.
       6           01 DATA-NAME PIC X.
       7           PROCEDURE DIVISION.
       8 >           DISPLAY DATA-NAME
    ----                     ^
       9             STOP RUN.
      10
    (line 7, character 18):
    List of completions: [DATA-NAME;ZEROS;SUPER;SPACES;SELF;QUOTES;PAGE-COUNTER;NULL;LOW-VALUES;LINE-COUNTER;LINAGE-COUNTER;HIGH-VALUES;FUNCTION;EXCEPTION-OBJECT;ALL;ADDRESS]
    __rootdir__/prog.cob:9.10:
       6           01 DATA-NAME PIC X.
       7           PROCEDURE DIVISION.
       8             DISPLAY DATA-NAME
       9 >           STOP RUN.
    ----             ^
      10
    (line 8, character 10):
    List of completions: [ZERO-FILL;ZEROS;WRITE;WORKING-STORAGE;WITH NO ADVANCING;WITH DATA;WITH;WHEN;VARYING;VALUES;VALUE;VAL-STATUS;VALIDATE;USING;USER-DEFAULT;USAGE;UPPER;UPON;UPDATE;UP;UNTIL;UNSTRING;UNLOCK;UNIT;UNDERLINE;TYPEDEF;TYPE;TRANSFORM;TRAILING-SIGN;TRAILING;TOP;TO;TIME-OUT;TIMES;THRU;THEN;TEXT;TEST;TERMINATE;TERMINAL;TALLYING;SYSTEM-OFFSET;SYSTEM-DEFAULT;SYNCHRONIZED;SYMBOLIC;SUPPRESS;SUPER;SUM;SUB-QUEUE-3;SUB-QUEUE-2;SUB-QUEUE-1;SUBTRACT;STRING;STOP;STEP;STATUS;START;SPACE-FILL;SPACES;SOURCES;SOURCE;SORT;SIZE;SIGNED;SIGN;SHORT;SHARING;SET;SEQUENTIAL;SEQUENCE;SEND;SELF;SELECT;SEGMENT-LIMIT;SEGMENT;SECURE;SECTION;SECONDS;SEARCH;SD;SCREEN;SAME;ROUNDED;RIGHT-JUSTIFY;REWRITE;REVERSE-VIDEO;REVERSED;RETURNING;RETURN;RETRY;RESUME;RESET;RESERVE;RERUN;REQUIRED;REPORTS;REPORT;REPLACING;RENAMES;REMAINDER;RELEASE;RELATIVE;REFERENCE;REEL;REDEFINES;RECORDS;RECORDING;RECORD;RECEIVE;READ;RAISING;RAISE;QUOTES;QUEUE;PURGE;PROPERTY;PROMPT;PROGRAM-POINTER;PROGRAM;PROCEDURE-POINTER;PROCEDURE;PREVIOUS;PRESENT;PREFIXED;POSITIVE;POSITION;POINTER;PICTURE;PHYSICAL;PERFORM;PAGE-COUNTER;PAGE;PADDING;PACKED-DECIMAL;OVERRIDE;OVERLINE;OVERFLOW;OUTPUT;ORGANIZATION;ORDER;OR;OPTIONS;OPTIONAL;OPEN;ON SIZE ERROR;ON OVERFLOW;ON EXCEPTION;ONLY;ON;OMITTED;OFF;OF;OCCURS;OBJECT-REFERENCE;OBJECT;NUMERIC-EDITED;NUMERIC;NULL;NO-ECHO;NO DATA;NOT ON SIZE ERROR;NOT ON OVERFLOW;NOT ON EXCEPTION;NOT INVALID KEY;NOT AT EOP;NOT AT END;NOT;NO;NEXT SENTENCE;NEXT;NEGATIVE;NEAREST-TO-ZERO;NATIONAL-EDITED;NATIONAL;MULTIPLY;MULTIPLE;MOVE;MODE;MESSAGE;MERGE;MEMORY;LOW-VALUES;LOWLIGHT;LOWER;LOCK;LOCAL-STORAGE;LOCALE;LINKAGE;LINE-COUNTER;LINES;LINE;LINAGE-COUNTER;LINAGE;LIMIT;LESS;LENGTH;LEFT-JUSTIFY;LEFTLINE;LEADING;LAST;LABEL;KEY;JUSTIFIED;I-O-CONTROL;I-O;IS TYPEDEF;IS GLOBAL;IS EXTERNAL;IS;IN-ARITHMETIC-RANGE;INVOKE;INVALID KEY;INVALID;INTRINSIC;INTO;INTERFACE;INSPECT;INPUT-OUTPUT;INPUT;INITIATE;INITIALIZED;INITIALIZE;INITIAL;INDEXED;INDEX;IN;IGNORING;IF;HIGH-VALUES;HIGHLIGHT;GROUP-USAGE;GROUP;GRID;GREATER;GOBACK;GO;GLOBAL;GIVING;GENERATE;FUNCTION-POINTER;FUNCTION;FULL;FROM;FREE;FORMAT;FOREVER;FOREGROUND-COLOR;FOR;FOOTING;FLOAT-SHORT;FLOAT-NOT-A-NUMBER-SIGNALING;FLOAT-NOT-A-NUMBER-QUIET;FLOAT-NOT-A-NUMBER;FLOAT-LONG;FLOAT-INFINITY;FLOAT-EXTENDED;FLOAT-DECIMAL-34;FLOAT-DECIMAL-16;FLOAT-BINARY-64;FLOAT-BINARY-32;FLOAT-BINARY-128;FIRST;FINAL;FILLER;FILE-CONTROL;FILE;FD;FARTHEST-FROM-ZERO;FALSE;FACTORY;EXTERNAL;EXTEND;EXPANDS;EXIT;EXCEPTION-OBJECT;EXCEPTION;EVERY;EVALUATE;ESI;ERROR;ERASE;EQUAL;EOP;ENVIRONMENT;ENTRY;ENTER;END-WRITE;END-UNSTRING;END-SUBTRACT;END-STRING;END-START;END-SEARCH;END-REWRITE;END-RETURN;END-RECEIVE;END-READ;END-PERFORM;END-OF-PAGE;END-MULTIPLY;END-IF;END-EVALUATE;END-DIVIDE;END-DISPLAY;END-DELETE;END-COMPUTE;END-CALL;END-ADD;END-ACCEPT;END;ENABLE;EMI;ELSE;EGI;DYNAMIC;DUPLICATES;DOWN;DIVIDE;DISPLAY;DISABLE;DESTINATION;DESCENDING;DEPENDING;DELIMITER;DELIMITED;DELETE;DEFAULT;DECIMAL-POINT;DEBUGGING;DATA RECORDS;DATA RECORD;DATA-POINTER;DATA;CURSOR;CURRENCY;CRT;COUNT;CONVERTING;CONTROLS;CONTROL;CONTINUE;CONTENT;CONSTANT;CONFIGURATION;COMP-X;COMP-N;COMP-9;COMP-6;COMP-5;COMP-4;COMP-3;COMP-2;COMP-15;COMP-10;COMP-1;COMP-0;COMPUTE;COMP;COMMUNICATION;COLS;COLUMN;COLLATING;COL;CODE-SET;CODE;CLOSE;CLASSIFICATION;CLASS;CHARACTERS;CHARACTER;CANCEL;CALL;B-XOR;B-OR;B-NOT;B-AND;BY;BOTTOM;BOOLEAN;BLOCK;BLINK;BLANK;BIT;BINARY-SHORT;BINARY-LONG;BINARY-DOUBLE;BINARY-C-LONG;BINARY-CHAR;BINARY;BELL;BEFORE;BASED;BACKGROUND-COLOR;AUTO;AT EOP;AT END;ATTRIBUTE;AT;ASSIGN;ASCENDING;AS;ARE;ANY;AND;ALTERNATE;ALTER;ALSO;ALPHANUMERIC-EDITED;ALPHANUMERIC;ALPHABETIC-UPPER;ALPHABETIC-LOWER;ALPHABETIC;ALPHABET;ALLOCATE;ALL;ALIGNED;AFTER;ADVANCING;ADDRESS;ADD;ACCESS;ACCEPT]
    __rootdir__/prog.cob:9.15:
       6           01 DATA-NAME PIC X.
       7           PROCEDURE DIVISION.
       8             DISPLAY DATA-NAME
       9 >           STOP RUN.
    ----                  ^
      10
    (line 8, character 15):
    List of completions: [DATA-NAME;ZEROS;WRITE;WITH DATA;WHEN;VALIDATE;UNSTRING;UNLOCK;TRANSFORM;THREAD;TERMINATE;SUPPRESS;SUBTRACT;STRING;STOP;START;SPACES;SORT;SET;SEND;SEARCH;RUN;REWRITE;RETURN;RESUME;RELEASE;RECEIVE;READ;RAISE;QUOTES;PURGE;PERFORM;OVERFLOW;OPEN;ON SIZE ERROR;ON OVERFLOW;ON EXCEPTION;NOT ON SIZE ERROR;NOT ON OVERFLOW;NOT ON EXCEPTION;NOT INVALID KEY;NOT AT EOP;NOT AT END;NEXT SENTENCE;MULTIPLY;MOVE;MERGE;LOW-VALUES;INVOKE;INVALID KEY;INSPECT;INITIATE;INITIALIZE;IF;HIGH-VALUES;GOBACK;GO;GENERATE;FREE;EXIT;EXCEPTION;EVALUATE;ERROR;EOP;ENTRY;ENTER;END-WRITE;END-UNSTRING;END-SUBTRACT;END-STRING;END-START;END-SEARCH;END-REWRITE;END-RETURN;END-RECEIVE;END-READ;END-PERFORM;END-OF-PAGE;END-MULTIPLY;END-IF;END-EVALUATE;END-DIVIDE;END-DISPLAY;END-DELETE;END-COMPUTE;END-CALL;END-ADD;END-ACCEPT;END;ENABLE;ELSE;DIVIDE;DISPLAY;DISABLE;DELETE;DATA;CONTINUE;COMPUTE;CLOSE;CANCEL;CALL;AT EOP;AT END;ALTER;ALLOCATE;ALL;ADD;ACCEPT]
    __rootdir__/prog.cob:9.19:
       6           01 DATA-NAME PIC X.
       7           PROCEDURE DIVISION.
       8             DISPLAY DATA-NAME
       9 >           STOP RUN.
    ----                      ^
      10
    (line 8, character 19):
    List of completions: [DATA-NAME;ZEROS;WRITE;WITH DATA;WHEN;VALIDATE;UNSTRING;UNLOCK;TRANSFORM;THREAD;TERMINATE;SUPPRESS;SUBTRACT;STRING;STOP;START;SPACES;SORT;SET;SEND;SEARCH;RUN;REWRITE;RETURN;RESUME;RELEASE;RECEIVE;READ;RAISE;QUOTES;PURGE;PERFORM;OVERFLOW;OPEN;ON SIZE ERROR;ON OVERFLOW;ON EXCEPTION;NOT ON SIZE ERROR;NOT ON OVERFLOW;NOT ON EXCEPTION;NOT INVALID KEY;NOT AT EOP;NOT AT END;NEXT SENTENCE;MULTIPLY;MOVE;MERGE;LOW-VALUES;INVOKE;INVALID KEY;INSPECT;INITIATE;INITIALIZE;IF;HIGH-VALUES;GOBACK;GO;GENERATE;FREE;EXIT;EXCEPTION;EVALUATE;ERROR;EOP;ENTRY;ENTER;END-WRITE;END-UNSTRING;END-SUBTRACT;END-STRING;END-START;END-SEARCH;END-REWRITE;END-RETURN;END-RECEIVE;END-READ;END-PERFORM;END-OF-PAGE;END-MULTIPLY;END-IF;END-EVALUATE;END-DIVIDE;END-DISPLAY;END-DELETE;END-COMPUTE;END-CALL;END-ADD;END-ACCEPT;END;ENABLE;ELSE;DIVIDE;DISPLAY;DISABLE;DELETE;DATA;CONTINUE;COMPUTE;CLOSE;CANCEL;CALL;AT EOP;AT END;ALTER;ALLOCATE;ALL;ADD;ACCEPT] |}];;

let%expect_test "datadiv-completion" =
  let end_with_postproc = complete_positions @@ extract_position_markers {cobol|
        IDENTIFICATION DIVISION.
        PROGRAM-ID. prog.
        DATA DIVISION.
        WORKING-STORAGE SECTION.
        01 _|_DATA-NAME _|_PIC X.
        _|_01 VAR PICTURE _|_X _|_USAGE _|_DISPLAY.
        PROCEDURE DIVISION.
          DISPLAY DATA-NAME.
          STOP RUN.
  |cobol} in
  end_with_postproc [%expect.output];
  [%expect {|
    {"params":{"diagnostics":[],"uri":"file://__rootdir__/prog.cob"},"method":"textDocument/publishDiagnostics","jsonrpc":"2.0"}
    __rootdir__/prog.cob:6.11:
       3           PROGRAM-ID. prog.
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
       6 >         01 DATA-NAME PIC X.
    ----              ^
       7           01 VAR PICTURE X USAGE DISPLAY.
       8           PROCEDURE DIVISION.
    (line 5, character 11):
    List of completions: [VARYING;VALUES;VALUE;VAL-STATUS;USAGE;TYPEDEF;TYPE;TRAILING;SYNCHRONIZED;SIGN;SELECT;SAME;REDEFINES;PROPERTY;PROGRAM-POINTER;PROCEDURE-POINTER;PRESENT;POINTER;PICTURE;PACKED-DECIMAL;OCCURS;OBJECT;NATIONAL;LEADING;JUSTIFIED;IS TYPEDEF;IS GLOBAL;IS EXTERNAL;INVALID;INDEX;GROUP-USAGE;GLOBAL;FUNCTION-POINTER;FLOAT-SHORT;FLOAT-LONG;FLOAT-EXTENDED;FLOAT-DECIMAL-34;FLOAT-DECIMAL-16;FLOAT-BINARY-64;FLOAT-BINARY-32;FLOAT-BINARY-128;FILLER;EXTERNAL;DYNAMIC;DISPLAY;DESTINATION;DEFAULT;COMP-X;COMP-N;COMP-9;COMP-6;COMP-5;COMP-4;COMP-3;COMP-2;COMP-15;COMP-10;COMP-1;COMP-0;COMP;CLASS;BLANK;BIT;BINARY-SHORT;BINARY-LONG;BINARY-DOUBLE;BINARY-C-LONG;BINARY-CHAR;BINARY;BASED;ANY;ALIGNED]
    __rootdir__/prog.cob:6.21:
       3           PROGRAM-ID. prog.
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
       6 >         01 DATA-NAME PIC X.
    ----                        ^
       7           01 VAR PICTURE X USAGE DISPLAY.
       8           PROCEDURE DIVISION.
    (line 5, character 21):
    List of completions: [ZERO-FILL;ZEROS;WRITE;WORKING-STORAGE;WITH NO ADVANCING;WITH DATA;WITH;WHEN;VARYING;VALUES;VALUE;VAL-STATUS;VALIDATE;USING;USER-DEFAULT;USAGE;UPPER;UPON;UPDATE;UP;UNTIL;UNSTRING;UNLOCK;UNIT;UNDERLINE;TYPEDEF;TYPE;TRANSFORM;TRAILING-SIGN;TRAILING;TOP;TO;TIME-OUT;TIMES;THRU;THEN;TEXT;TEST;TERMINATE;TERMINAL;TALLYING;SYSTEM-OFFSET;SYSTEM-DEFAULT;SYNCHRONIZED;SYMBOLIC;SUPPRESS;SUPER;SUM;SUB-QUEUE-3;SUB-QUEUE-2;SUB-QUEUE-1;SUBTRACT;STRING;STOP;STEP;STATUS;START;SPACE-FILL;SPACES;SOURCES;SOURCE;SORT;SIZE;SIGNED;SIGN;SHORT;SHARING;SET;SEQUENTIAL;SEQUENCE;SEND;SELF;SELECT;SEGMENT-LIMIT;SEGMENT;SECURE;SECTION;SECONDS;SEARCH;SD;SCREEN;SAME;ROUNDED;RIGHT-JUSTIFY;REWRITE;REVERSE-VIDEO;REVERSED;RETURNING;RETURN;RETRY;RESUME;RESET;RESERVE;RERUN;REQUIRED;REPORTS;REPORT;REPLACING;RENAMES;REMAINDER;RELEASE;RELATIVE;REFERENCE;REEL;REDEFINES;RECORDS;RECORDING;RECORD;RECEIVE;READ;RAISING;RAISE;QUOTES;QUEUE;PURGE;PROPERTY;PROMPT;PROGRAM-POINTER;PROGRAM;PROCEDURE-POINTER;PROCEDURE;PREVIOUS;PRESENT;PREFIXED;POSITIVE;POSITION;POINTER;PICTURE;PHYSICAL;PERFORM;PAGE-COUNTER;PAGE;PADDING;PACKED-DECIMAL;OVERRIDE;OVERLINE;OVERFLOW;OUTPUT;ORGANIZATION;ORDER;OR;OPTIONS;OPTIONAL;OPEN;ON SIZE ERROR;ON OVERFLOW;ON EXCEPTION;ONLY;ON;OMITTED;OFF;OF;OCCURS;OBJECT-REFERENCE;OBJECT;NUMERIC-EDITED;NUMERIC;NULL;NO-ECHO;NO DATA;NOT ON SIZE ERROR;NOT ON OVERFLOW;NOT ON EXCEPTION;NOT INVALID KEY;NOT AT EOP;NOT AT END;NOT;NO;NEXT SENTENCE;NEXT;NEGATIVE;NEAREST-TO-ZERO;NATIONAL-EDITED;NATIONAL;MULTIPLY;MULTIPLE;MOVE;MODE;MESSAGE;MERGE;MEMORY;LOW-VALUES;LOWLIGHT;LOWER;LOCK;LOCAL-STORAGE;LOCALE;LINKAGE;LINE-COUNTER;LINES;LINE;LINAGE-COUNTER;LINAGE;LIMIT;LESS;LENGTH;LEFT-JUSTIFY;LEFTLINE;LEADING;LAST;LABEL;KEY;JUSTIFIED;I-O-CONTROL;I-O;IS TYPEDEF;IS GLOBAL;IS EXTERNAL;IS;IN-ARITHMETIC-RANGE;INVOKE;INVALID KEY;INVALID;INTRINSIC;INTO;INTERFACE;INSPECT;INPUT-OUTPUT;INPUT;INITIATE;INITIALIZED;INITIALIZE;INITIAL;INDEXED;INDEX;IN;IGNORING;IF;HIGH-VALUES;HIGHLIGHT;GROUP-USAGE;GROUP;GRID;GREATER;GOBACK;GO;GLOBAL;GIVING;GENERATE;FUNCTION-POINTER;FUNCTION;FULL;FROM;FREE;FORMAT;FOREVER;FOREGROUND-COLOR;FOR;FOOTING;FLOAT-SHORT;FLOAT-NOT-A-NUMBER-SIGNALING;FLOAT-NOT-A-NUMBER-QUIET;FLOAT-NOT-A-NUMBER;FLOAT-LONG;FLOAT-INFINITY;FLOAT-EXTENDED;FLOAT-DECIMAL-34;FLOAT-DECIMAL-16;FLOAT-BINARY-64;FLOAT-BINARY-32;FLOAT-BINARY-128;FIRST;FINAL;FILLER;FILE-CONTROL;FILE;FD;FARTHEST-FROM-ZERO;FALSE;FACTORY;EXTERNAL;EXTEND;EXPANDS;EXIT;EXCEPTION-OBJECT;EXCEPTION;EVERY;EVALUATE;ESI;ERROR;ERASE;EQUAL;EOP;ENVIRONMENT;ENTRY;ENTER;END-WRITE;END-UNSTRING;END-SUBTRACT;END-STRING;END-START;END-SEARCH;END-REWRITE;END-RETURN;END-RECEIVE;END-READ;END-PERFORM;END-OF-PAGE;END-MULTIPLY;END-IF;END-EVALUATE;END-DIVIDE;END-DISPLAY;END-DELETE;END-COMPUTE;END-CALL;END-ADD;END-ACCEPT;END;ENABLE;EMI;ELSE;EGI;DYNAMIC;DUPLICATES;DOWN;DIVIDE;DISPLAY;DISABLE;DESTINATION;DESCENDING;DEPENDING;DELIMITER;DELIMITED;DELETE;DEFAULT;DECIMAL-POINT;DEBUGGING;DATA RECORDS;DATA RECORD;DATA-POINTER;DATA;CURSOR;CURRENCY;CRT;COUNT;CONVERTING;CONTROLS;CONTROL;CONTINUE;CONTENT;CONSTANT;CONFIGURATION;COMP-X;COMP-N;COMP-9;COMP-6;COMP-5;COMP-4;COMP-3;COMP-2;COMP-15;COMP-10;COMP-1;COMP-0;COMPUTE;COMP;COMMUNICATION;COLS;COLUMN;COLLATING;COL;CODE-SET;CODE;CLOSE;CLASSIFICATION;CLASS;CHARACTERS;CHARACTER;CANCEL;CALL;B-XOR;B-OR;B-NOT;B-AND;BY;BOTTOM;BOOLEAN;BLOCK;BLINK;BLANK;BIT;BINARY-SHORT;BINARY-LONG;BINARY-DOUBLE;BINARY-C-LONG;BINARY-CHAR;BINARY;BELL;BEFORE;BASED;BACKGROUND-COLOR;AUTO;AT EOP;AT END;ATTRIBUTE;AT;ASSIGN;ASCENDING;AS;ARE;ANY;AND;ALTERNATE;ALTER;ALSO;ALPHANUMERIC-EDITED;ALPHANUMERIC;ALPHABETIC-UPPER;ALPHABETIC-LOWER;ALPHABETIC;ALPHABET;ALLOCATE;ALL;ALIGNED;AFTER;ADVANCING;ADDRESS;ADD;ACCESS;ACCEPT]
    __rootdir__/prog.cob:7.8:
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
       6           01 DATA-NAME PIC X.
       7 >         01 VAR PICTURE X USAGE DISPLAY.
    ----           ^
       8           PROCEDURE DIVISION.
       9             DISPLAY DATA-NAME.
    (line 6, character 8):
    List of completions: [WORKING-STORAGE;SD;SCREEN;REPORT;PROGRAM-ID;PROCEDURE;LOCAL-STORAGE;LINKAGE;IDENTIFICATION;ID;FILE;FD;END;DATA;COMMUNICATION;CD]
    __rootdir__/prog.cob:7.23:
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
       6           01 DATA-NAME PIC X.
       7 >         01 VAR PICTURE X USAGE DISPLAY.
    ----                          ^
       8           PROCEDURE DIVISION.
       9             DISPLAY DATA-NAME.
    (line 6, character 23):
    List of completions: [IS]
    __rootdir__/prog.cob:7.25:
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
       6           01 DATA-NAME PIC X.
       7 >         01 VAR PICTURE X USAGE DISPLAY.
    ----                            ^
       8           PROCEDURE DIVISION.
       9             DISPLAY DATA-NAME.
    (line 6, character 25):
    List of completions: [ZERO-FILL;VARYING;VALUES;VALUE;VAL-STATUS;USING;USAGE;UNDERLINE;TYPEDEF;TYPE;TRAILING;TO;SYNCHRONIZED;SUM;SOURCES;SOURCE;SIZE;SIGN;SELECT;SECURE;SAME;REVERSE-VIDEO;REQUIRED;REDEFINES;PROPERTY;PROMPT;PROGRAM-POINTER;PROCEDURE-POINTER;PRESENT;POINTER;PICTURE;PACKED-DECIMAL;OVERLINE;OCCURS;OBJECT;NO-ECHO;NEXT;NATIONAL;LOWLIGHT;LOCALE;LINES;LINE;LEFTLINE;LEADING;JUSTIFIED;IS TYPEDEF;IS GLOBAL;IS EXTERNAL;INVALID;INDEX;HIGHLIGHT;GROUP-USAGE;GROUP;GRID;GLOBAL;FUNCTION-POINTER;FULL;FROM;FOREGROUND-COLOR;FLOAT-SHORT;FLOAT-LONG;FLOAT-EXTENDED;FLOAT-DECIMAL-34;FLOAT-DECIMAL-16;FLOAT-BINARY-64;FLOAT-BINARY-32;FLOAT-BINARY-128;EXTERNAL;ERASE;DYNAMIC;DISPLAY;DESTINATION;DEPENDING;DEFAULT;CONTROL;COMP-X;COMP-N;COMP-9;COMP-6;COMP-5;COMP-4;COMP-3;COMP-2;COMP-15;COMP-10;COMP-1;COMP-0;COMP;COLS;COLUMN;COL;CLASS;BLINK;BLANK;BIT;BINARY-SHORT;BINARY-LONG;BINARY-DOUBLE;BINARY-C-LONG;BINARY-CHAR;BINARY;BELL;BASED;BACKGROUND-COLOR;AUTO;ANY;ALIGNED]
    __rootdir__/prog.cob:7.31:
       4           DATA DIVISION.
       5           WORKING-STORAGE SECTION.
       6           01 DATA-NAME PIC X.
       7 >         01 VAR PICTURE X USAGE DISPLAY.
    ----                                  ^
       8           PROCEDURE DIVISION.
       9             DISPLAY DATA-NAME.
    (line 6, character 31):
    List of completions: [PROGRAM-POINTER;PROCEDURE-POINTER;POINTER;PACKED-DECIMAL;OBJECT;NATIONAL;IS;INDEX;FUNCTION-POINTER;FLOAT-SHORT;FLOAT-LONG;FLOAT-EXTENDED;FLOAT-DECIMAL-34;FLOAT-DECIMAL-16;FLOAT-BINARY-64;FLOAT-BINARY-32;FLOAT-BINARY-128;DISPLAY;COMP-X;COMP-N;COMP-9;COMP-6;COMP-5;COMP-4;COMP-3;COMP-2;COMP-15;COMP-10;COMP-1;COMP-0;COMP;BIT;BINARY-SHORT;BINARY-LONG;BINARY-DOUBLE;BINARY-C-LONG;BINARY-CHAR;BINARY] |}]

let%expect_test "procedurename-completion" =
  let end_with_postproc = complete_positions @@ extract_position_markers {cobol|
        IDENTIFICATION DIVISION.
        PROGRAM-ID. prog.
        DATA DIVISION.
        WORKING-STORAGE SECTION.
        01 DATA-NAME PIC X.
        01 VAR PICTURE X USAGE DISPLAY.
        PROCEDURE DIVISION.
          _|_FIRST-SECTION _|_SECTION.
            _|_DISPLAY DATA-NAME.
          _|_FIRST-PARAGRAPH.
            DISPLAY VAR.
            SECOND-SECTION SECTION.
              PERFORM _|_FIRST-PARAGRAPH.
          STOP RUN.
  |cobol} in
  end_with_postproc [%expect.output];
  [%expect {|
    {"params":{"diagnostics":[],"uri":"file://__rootdir__/prog.cob"},"method":"textDocument/publishDiagnostics","jsonrpc":"2.0"}
    __rootdir__/prog.cob:9.10:
       6           01 DATA-NAME PIC X.
       7           01 VAR PICTURE X USAGE DISPLAY.
       8           PROCEDURE DIVISION.
       9 >           FIRST-SECTION SECTION.
    ----             ^
      10               DISPLAY DATA-NAME.
      11             FIRST-PARAGRAPH.
    (line 8, character 10):
    List of completions: [WRITE;VALIDATE;UNSTRING;UNLOCK;TRANSFORM;TERMINATE;SUPPRESS;SUBTRACT;STRING;STOP;START;SORT;SET;SEND;SEARCH;REWRITE;RETURN;RESUME;RELEASE;RECEIVE;READ;RAISE;PURGE;PROGRAM-ID;PERFORM;OPEN;NEXT SENTENCE;MULTIPLY;MOVE;MERGE;INVOKE;INSPECT;INITIATE;INITIALIZE;IF;IDENTIFICATION;ID;GOBACK;GO;GENERATE;FREE;EXIT;EVALUATE;ENTRY;ENTER;END;ENABLE;DIVIDE;DISPLAY;DISABLE;DELETE;DECLARATIVES;CONTINUE;COMPUTE;CLOSE;CANCEL;CALL;ALTER;ALLOCATE;ADD;ACCEPT]
    __rootdir__/prog.cob:9.24:
       6           01 DATA-NAME PIC X.
       7           01 VAR PICTURE X USAGE DISPLAY.
       8           PROCEDURE DIVISION.
       9 >           FIRST-SECTION SECTION.
    ----                           ^
      10               DISPLAY DATA-NAME.
      11             FIRST-PARAGRAPH.
    (line 8, character 24):
    List of completions: [ZERO-FILL;ZEROS;WRITE;WORKING-STORAGE;WITH NO ADVANCING;WITH DATA;WITH;WHEN;VARYING;VALUES;VALUE;VAL-STATUS;VALIDATE;USING;USER-DEFAULT;USAGE;UPPER;UPON;UPDATE;UP;UNTIL;UNSTRING;UNLOCK;UNIT;UNDERLINE;TYPEDEF;TYPE;TRANSFORM;TRAILING-SIGN;TRAILING;TOP;TO;TIME-OUT;TIMES;THRU;THEN;TEXT;TEST;TERMINATE;TERMINAL;TALLYING;SYSTEM-OFFSET;SYSTEM-DEFAULT;SYNCHRONIZED;SYMBOLIC;SUPPRESS;SUPER;SUM;SUB-QUEUE-3;SUB-QUEUE-2;SUB-QUEUE-1;SUBTRACT;STRING;STOP;STEP;STATUS;START;SPACE-FILL;SPACES;SOURCES;SOURCE;SORT;SIZE;SIGNED;SIGN;SHORT;SHARING;SET;SEQUENTIAL;SEQUENCE;SEND;SELF;SELECT;SEGMENT-LIMIT;SEGMENT;SECURE;SECTION;SECONDS;SEARCH;SD;SCREEN;SAME;ROUNDED;RIGHT-JUSTIFY;REWRITE;REVERSE-VIDEO;REVERSED;RETURNING;RETURN;RETRY;RESUME;RESET;RESERVE;RERUN;REQUIRED;REPORTS;REPORT;REPLACING;RENAMES;REMAINDER;RELEASE;RELATIVE;REFERENCE;REEL;REDEFINES;RECORDS;RECORDING;RECORD;RECEIVE;READ;RAISING;RAISE;QUOTES;QUEUE;PURGE;PROPERTY;PROMPT;PROGRAM-POINTER;PROGRAM;PROCEDURE-POINTER;PROCEDURE;PREVIOUS;PRESENT;PREFIXED;POSITIVE;POSITION;POINTER;PICTURE;PHYSICAL;PERFORM;PAGE-COUNTER;PAGE;PADDING;PACKED-DECIMAL;OVERRIDE;OVERLINE;OVERFLOW;OUTPUT;ORGANIZATION;ORDER;OR;OPTIONS;OPTIONAL;OPEN;ON SIZE ERROR;ON OVERFLOW;ON EXCEPTION;ONLY;ON;OMITTED;OFF;OF;OCCURS;OBJECT-REFERENCE;OBJECT;NUMERIC-EDITED;NUMERIC;NULL;NO-ECHO;NO DATA;NOT ON SIZE ERROR;NOT ON OVERFLOW;NOT ON EXCEPTION;NOT INVALID KEY;NOT AT EOP;NOT AT END;NOT;NO;NEXT SENTENCE;NEXT;NEGATIVE;NEAREST-TO-ZERO;NATIONAL-EDITED;NATIONAL;MULTIPLY;MULTIPLE;MOVE;MODE;MESSAGE;MERGE;MEMORY;LOW-VALUES;LOWLIGHT;LOWER;LOCK;LOCAL-STORAGE;LOCALE;LINKAGE;LINE-COUNTER;LINES;LINE;LINAGE-COUNTER;LINAGE;LIMIT;LESS;LENGTH;LEFT-JUSTIFY;LEFTLINE;LEADING;LAST;LABEL;KEY;JUSTIFIED;I-O-CONTROL;I-O;IS TYPEDEF;IS GLOBAL;IS EXTERNAL;IS;IN-ARITHMETIC-RANGE;INVOKE;INVALID KEY;INVALID;INTRINSIC;INTO;INTERFACE;INSPECT;INPUT-OUTPUT;INPUT;INITIATE;INITIALIZED;INITIALIZE;INITIAL;INDEXED;INDEX;IN;IGNORING;IF;HIGH-VALUES;HIGHLIGHT;GROUP-USAGE;GROUP;GRID;GREATER;GOBACK;GO;GLOBAL;GIVING;GENERATE;FUNCTION-POINTER;FUNCTION;FULL;FROM;FREE;FORMAT;FOREVER;FOREGROUND-COLOR;FOR;FOOTING;FLOAT-SHORT;FLOAT-NOT-A-NUMBER-SIGNALING;FLOAT-NOT-A-NUMBER-QUIET;FLOAT-NOT-A-NUMBER;FLOAT-LONG;FLOAT-INFINITY;FLOAT-EXTENDED;FLOAT-DECIMAL-34;FLOAT-DECIMAL-16;FLOAT-BINARY-64;FLOAT-BINARY-32;FLOAT-BINARY-128;FIRST;FINAL;FILLER;FILE-CONTROL;FILE;FD;FARTHEST-FROM-ZERO;FALSE;FACTORY;EXTERNAL;EXTEND;EXPANDS;EXIT;EXCEPTION-OBJECT;EXCEPTION;EVERY;EVALUATE;ESI;ERROR;ERASE;EQUAL;EOP;ENVIRONMENT;ENTRY;ENTER;END-WRITE;END-UNSTRING;END-SUBTRACT;END-STRING;END-START;END-SEARCH;END-REWRITE;END-RETURN;END-RECEIVE;END-READ;END-PERFORM;END-OF-PAGE;END-MULTIPLY;END-IF;END-EVALUATE;END-DIVIDE;END-DISPLAY;END-DELETE;END-COMPUTE;END-CALL;END-ADD;END-ACCEPT;END;ENABLE;EMI;ELSE;EGI;DYNAMIC;DUPLICATES;DOWN;DIVIDE;DISPLAY;DISABLE;DESTINATION;DESCENDING;DEPENDING;DELIMITER;DELIMITED;DELETE;DEFAULT;DECIMAL-POINT;DEBUGGING;DATA RECORDS;DATA RECORD;DATA-POINTER;DATA;CURSOR;CURRENCY;CRT;COUNT;CONVERTING;CONTROLS;CONTROL;CONTINUE;CONTENT;CONSTANT;CONFIGURATION;COMP-X;COMP-N;COMP-9;COMP-6;COMP-5;COMP-4;COMP-3;COMP-2;COMP-15;COMP-10;COMP-1;COMP-0;COMPUTE;COMP;COMMUNICATION;COLS;COLUMN;COLLATING;COL;CODE-SET;CODE;CLOSE;CLASSIFICATION;CLASS;CHARACTERS;CHARACTER;CANCEL;CALL;B-XOR;B-OR;B-NOT;B-AND;BY;BOTTOM;BOOLEAN;BLOCK;BLINK;BLANK;BIT;BINARY-SHORT;BINARY-LONG;BINARY-DOUBLE;BINARY-C-LONG;BINARY-CHAR;BINARY;BELL;BEFORE;BASED;BACKGROUND-COLOR;AUTO;AT EOP;AT END;ATTRIBUTE;AT;ASSIGN;ASCENDING;AS;ARE;ANY;AND;ALTERNATE;ALTER;ALSO;ALPHANUMERIC-EDITED;ALPHANUMERIC;ALPHABETIC-UPPER;ALPHABETIC-LOWER;ALPHABETIC;ALPHABET;ALLOCATE;ALL;ALIGNED;AFTER;ADVANCING;ADDRESS;ADD;ACCESS;ACCEPT]
    __rootdir__/prog.cob:10.12:
       7           01 VAR PICTURE X USAGE DISPLAY.
       8           PROCEDURE DIVISION.
       9             FIRST-SECTION SECTION.
      10 >             DISPLAY DATA-NAME.
    ----               ^
      11             FIRST-PARAGRAPH.
      12               DISPLAY VAR.
    (line 9, character 12):
    List of completions: [WRITE;VALIDATE;UNSTRING;UNLOCK;TRANSFORM;TERMINATE;SUPPRESS;SUBTRACT;STRING;STOP;START;SORT;SET;SEND;SEARCH;REWRITE;RETURN;RESUME;RELEASE;RECEIVE;READ;RAISE;PURGE;PROGRAM-ID;PERFORM;OPEN;NEXT SENTENCE;MULTIPLY;MOVE;MERGE;INVOKE;INSPECT;INITIATE;INITIALIZE;IF;IDENTIFICATION;ID;GOBACK;GO;GENERATE;FREE;EXIT;EVALUATE;ENTRY;ENTER;END;ENABLE;DIVIDE;DISPLAY;DISABLE;DELETE;CONTINUE;COMPUTE;CLOSE;CANCEL;CALL;ALTER;ALLOCATE;ADD;ACCEPT]
    __rootdir__/prog.cob:11.10:
       8           PROCEDURE DIVISION.
       9             FIRST-SECTION SECTION.
      10               DISPLAY DATA-NAME.
      11 >           FIRST-PARAGRAPH.
    ----             ^
      12               DISPLAY VAR.
      13               SECOND-SECTION SECTION.
    (line 10, character 10):
    List of completions: [WRITE;VALIDATE;UNSTRING;UNLOCK;TRANSFORM;TERMINATE;SUPPRESS;SUBTRACT;STRING;STOP;START;SORT;SET;SEND;SEARCH;REWRITE;RETURN;RESUME;RELEASE;RECEIVE;READ;RAISE;PURGE;PROGRAM-ID;PERFORM;OPEN;NEXT SENTENCE;MULTIPLY;MOVE;MERGE;INVOKE;INSPECT;INITIATE;INITIALIZE;IF;IDENTIFICATION;ID;GOBACK;GO;GENERATE;FREE;EXIT;EVALUATE;ENTRY;ENTER;END;ENABLE;DIVIDE;DISPLAY;DISABLE;DELETE;CONTINUE;COMPUTE;CLOSE;CANCEL;CALL;ALTER;ALLOCATE;ADD;ACCEPT]
    __rootdir__/prog.cob:14.22:
      11             FIRST-PARAGRAPH.
      12               DISPLAY VAR.
      13               SECOND-SECTION SECTION.
      14 >               PERFORM FIRST-PARAGRAPH.
    ----                         ^
      15             STOP RUN.
      16
    (line 13, character 22):
    List of completions: [DATA-NAME;VAR;FIRST-SECTION;FIRST-PARAGRAPH;FIRST-PARAGRAPH IN FIRST-SECTION;SECOND-SECTION;ZEROS;WRITE;WITH;VARYING;VALIDATE;UNTIL;UNSTRING;UNLOCK;TRANSFORM;TEST;TERMINATE;SUPPRESS;SUPER;SUBTRACT;STRING;STOP;START;SORT;SET;SEND;SELF;SEARCH;REWRITE;RETURN;RESUME;RELEASE;RECEIVE;READ;RAISE;PURGE;PERFORM;PAGE-COUNTER;OPEN;NULL;NEXT SENTENCE;MULTIPLY;MOVE;MERGE;LINE-COUNTER;LINAGE-COUNTER;INVOKE;INSPECT;INITIATE;INITIALIZE;IF;GOBACK;GO;GENERATE;FUNCTION;FREE;FOREVER;EXIT;EXCEPTION-OBJECT;EVALUATE;ENTRY;ENTER;END-PERFORM;ENABLE;DIVIDE;DISPLAY;DISABLE;DELETE;CONTINUE;COMPUTE;CLOSE;CANCEL;CALL;ALTER;ALLOCATE;ADDRESS;ADD;ACCEPT] |}]
