(* Caution: this file was automatically generated from compdir_grammar.cmly; do not edit *)
[@@@warning "-33"] (* <- do not warn on unused opens *)

let keywords = Compdir_grammar.[
  "TO", TO;
  "THAN", THAN;
  "SSRANGE", SSRANGE;
  "SPZERO", SPZERO;
  "SOURCEFORMAT", SOURCEFORMAT;
  "SET", SET;
  "REMOVE", REMOVE;
  "PARAMETER", PARAMETER;
  "OVERRIDE", OVERRIDE;
  "OR", OR;
  "OFF", OFF;
  "ODOSLIDE", ODOSLIDE;
  "NOT", NOT;
  "NOSSRANGE", NOSSRANGE;
  "NO-SSRANGE", NOSSRANGE;
  "NOSPZERO", NOSPZERO;
  "NO-SPZERO", NOSPZERO;
  "NOODOSLIDE", NOODOSLIDE;
  "NO-ODOSLIDE", NOODOSLIDE;
  "NOFOLDCOPYNAME", NOFOLDCOPYNAME;
  "NOFOLD-COPY-NAME", NOFOLDCOPYNAME;
  "NO-FOLD-COPY-NAME", NOFOLDCOPYNAME;
  "NODPCINDATA", NODPC_IN_DATA;
  "NO-DPCINDATA", NODPC_IN_DATA;
  "NODPC-IN-DATA", NODPC_IN_DATA;
  "NO-DPC-IN-DATA", NODPC_IN_DATA;
  "NOCHECKNUM", NOCHECKNUM;
  "NO-CHECKNUM", NOCHECKNUM;
  "NO-CHECK-NUM", NOCHECKNUM;
  "NOBOUND", NOBOUND;
  "NO-BOUND", NOBOUND;
  "NOAREACHECK", NOAREACHECK;
  "NO-AREACHECK", NOAREACHECK;
  "NO-AREA-CHECK", NOAREACHECK;
  "NESTCALL", NESTCALL;
  "MAKESYN", MAKESYN;
  "MAKE-SYN", MAKESYN;
  "LESS", LESS;
  "IS", IS;
  "GREATER", GREATER;
  "FREE", FREE;
  "FORMAT", FORMAT;
  "FOLDCOPYNAME", FOLDCOPYNAME;
  "FOLD-COPY-NAME", FOLDCOPYNAME;
  "EQUAL", EQUAL;
  "DPCINDATA", DPCINDATA;
  "DPC-IN-DATA", DPCINDATA;
  "DEFINED", DEFINED;
  "CONSTANT", CONSTANT;
  "COMP1", COMP1;
  "COMP-1", COMP1;
  "CHECKNUM", CHECKNUM;
  "CHECK-NUM", CHECKNUM;
  ">>SOURCE", CDIR_SOURCE;
  "$SOURCE", CDIR_SOURCE;
  ">>SET", CDIR_SET;
  "$SET", CDIR_SET;
  ">>IF", CDIR_IF;
  ">>END-IF", CDIR_END_IF;
  ">>ELSE", CDIR_ELSE;
  ">>ELIF", CDIR_ELIF;
  ">>ELSE-IF", CDIR_ELIF;
  ">>DEFINE", CDIR_DEFINE;
  "$DEFINE", CDIR_DEFINE;
  "CALLFH", CALLFH;
  "BOUND", BOUND;
  "ASSIGN", ASSIGN;
  "AS", AS;
  "AREACHECK", AREACHECK;
  "AREA-CHECK", AREACHECK;
  "ADDSYN", ADDSYN;
  "ADD-SYN", ADDSYN;
  "ADDRSV", ADDRSV;
  "ADD-RSV", ADDRSV;
]

let puncts = Compdir_grammar.[
]

let silenced_keywords = Compdir_grammar.[
]

